### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by ziriax** [picturepan2/instagram.css#26]
Thanks for this great library!

I was wondering, is it actually legal to use these filter effect on websites and commercial platforms?

Does Instagram allow this?

Surely the names themselves must have a trademark on them?

And what about the algorithms? I guess these approximate the original Instagram effects, not being pixel perfect copies?

**Comment by picturepan2** [comment]
@Ziriax For a nonprofit open source project, it is OK. But for commercial projects, it is better to talk to lawyers.
