### ISSUE TITLE
What's the difference with CSSgram?

### ISSUE THREAD

**Issue by serchavalos** [picturepan2/instagram.css#6]
I looked at the readme and I saw it was inspired by CSSgram but I couldn't understand exactly what the difference is. Could you elaborate on it?

**Comment by lulucca12** [comment]
Its like a "fork" but its intended to add more things and do not be a library and just a collection

**Comment by serchavalos** [comment]
But why not to add those things to the same project?

**Comment by soanvig** [comment]
As I see CSSgram has global class names, which is **bad**.

**Comment by picturepan2** [comment]
@serchavalos Yes, Instagram.css is inspired by CSSgram. But CSSgram is way too complex that makes adding new filters difficult than I thought. Some of its filters are not perfect as I tested.
